[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd server && npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd server && npm run build"
]

[start]
cmd = "node server/dist/index.js"
