export const CHANNELS = {
  authStartLogin: 'auth:start-login',
  authOpenLogin: 'auth:open-login',
  authSetSession: 'auth:set-session',
  authGetSession: 'auth:get-session',
  authClearSession: 'auth:clear-session',
  authCallback: 'auth:callback',

  windowMinimize: 'window:minimize',
  windowClose: 'window:close',
  windowHide: 'window:hide',
  windowSetAlwaysOnTop: 'window:set-always-on-top',
  windowSetMode: 'window:set-mode',
  windowGetBounds: 'window:get-bounds',
  windowMoveTo: 'window:move-to',
  windowPositionPreset: 'window:position-preset',
  windowNudge: 'window:nudge',
  windowRestoreTaskbar: 'window:restore-taskbar',
  windowSetSignedInReady: 'window:set-signed-in-ready',
  windowCollapsed: 'window:collapsed',

  captureScreen: 'capture:screen',
  captureActiveWindow: 'capture:active-window',
  captureRegion: 'capture:region',

  audioGetSources: 'audio:get-sources',
  audioStartCapture: 'audio:start-capture',
  audioStopCapture: 'audio:stop-capture',
  audioChunk: 'audio:chunk',

  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsChanged: 'settings:changed',
  planVisibility: 'plan:visibility',

  shortcutsGet: 'shortcuts:get',
  shortcutsGetFailed: 'shortcuts:get-failed',
  shortcutsSet: 'shortcuts:set',
  shortcutsReset: 'shortcuts:reset',
  shortcutsSuspend: 'shortcuts:suspend',
  shortcutsChanged: 'shortcuts:changed',
  shortcutsFailed: 'shortcuts:failed',

  conversationsList: 'conversations:list',
  conversationsGet: 'conversations:get',
  conversationsSave: 'conversations:save',
  conversationsDelete: 'conversations:delete',
  conversationsClear: 'conversations:clear',

  profileGet: 'profile:get',
  profileSet: 'profile:set',
  profileComplete: 'profile:complete',
  profileSaveResume: 'profile:save-resume',
  profileDeleteResume: 'profile:delete-resume',

  aiChat: 'ai:chat',
  aiStop: 'ai:stop',
  aiChunk: 'ai:chunk',
  aiDone: 'ai:done',
  aiError: 'ai:error',

  appQuit: 'app:quit',
  appOpenExternal: 'app:open-external',
  appPickFiles: 'app:pick-files',
  appCommand: 'app:command',
  appNotify: 'app:notify',
  appDeleteLocalData: 'app:delete-local-data',
  appGetApiKeyStatus: 'app:api-key-status',
  appSetApiKey: 'app:set-api-key',
  appClearApiKey: 'app:clear-api-key',
  appSetPin: 'app:set-pin',
  appClearPin: 'app:clear-pin',
  appUnlock: 'app:unlock',
  appLock: 'app:lock',
  appGetLockState: 'app:lock-state',
  appGetVersion: 'app:get-version',
} as const
